/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Articles;
import jooq.tables.Authors;
import jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>articles</code>.
     */
    public static final Articles ARTICLES = jooq.tables.Articles.ARTICLES;

    /**
     * The table <code>authors</code>.
     */
    public static final Authors AUTHORS = jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
