/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.tables.Test;
import jooq.tables.records.TestRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestDao extends DAOImpl<TestRecord, jooq.tables.pojos.Test, Integer> {

    /**
     * Create a new TestDao without any configuration
     */
    public TestDao() {
        super(Test.TEST, jooq.tables.pojos.Test.class);
    }

    /**
     * Create a new TestDao with an attached configuration
     */
    public TestDao(Configuration configuration) {
        super(Test.TEST, jooq.tables.pojos.Test.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(jooq.tables.pojos.Test object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.tables.pojos.Test> fetchById(Integer... values) {
        return fetch(Test.TEST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.tables.pojos.Test fetchOneById(Integer value) {
        return fetchOne(Test.TEST.ID, value);
    }

    /**
     * Fetch records that have <code>test IN (values)</code>
     */
    public List<jooq.tables.pojos.Test> fetchByTest(Integer... values) {
        return fetch(Test.TEST.TEST_, values);
    }
}
